version: '3.9'

services:
  client:
     container_name: yolo-client
     build: ./client
     ports: 
       - "3000:3000"
     depends_on:
       - backend
     networks:
       - yolo-network 
  backend:
     container_name: yolo-backend
     build: ./backend
     environment:
       - MONGODB_URI=mongodb://yolo-mongodb:27017
     ports: 
       - "5000:5000"
     depends_on:
       - database
     networks: 
       - yolo-network
  database:
     image: egcharchi/yolo-mongodb:1.0.0
     container_name: yolo-mongodb
     ports:
      - "27017:27017"
     networks:
      - yolo-network
     volumes: 
      - ./data:/data/db
networks:
  yolo-network:
    name: yolo-network
    driver: bridge

