# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend-deployment
spec:
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
      - name: yolo-backend
        image: me-central1-docker.pkg.dev/moringak8s-382916/ip4-repo1/yolo-backend-k8s:1.0.0
        resources:
          requests:
            memory: "2Gi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "500m"
        ports:
        - containerPort: 5000
    #volumes:
    #  - name: data
     #   persistentVolumeClaim:
      #    claimName: yolo-mongodb-data
---
#Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: yolo-backend-svc
spec:
  selector:
    app: yolo
  ports:
  - port: 5000
    targetPort: 5000
  type: NodePort
