apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app-deploy
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: yolo-frontend
        image: egcharchi/yolo-frontend-k8s
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
