##Mongo Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-mongodb-deployment
spec:
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
      - name: yolo-mongodb
        image: me-central1-docker.pkg.dev/moringak8s-382916/ip4-repo1/yolo-mongodb-k8s:1.0.0
        resources:
          requests:
            memory: "2Gi"
            cpu: "200m"
          limits:
            memory: "8Gi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: yolo-mongodb-data
---
# Persistent Volume Claim - Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yolo-mongodb-data
  labels: 
    app: yolo
spec:
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
#Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: yolo-mongo-svc
spec:
  selector:
    app: yolo
  ports:
  - port: 27017
    targetPort: 27017
  type: NodePort


