# Client Side Container - Frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client-deployment
spec:
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
      - name: yolo-client
        image: me-central1-docker.pkg.dev/moringak8s-382916/ip4-repo1/yolo-client-k8s:1.0.0
        resources:
          requests:
            memory: "1Gi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "250m"
        ports:
        - containerPort: 3000
---
#Frontend Service - Nodeport
apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend-svc
spec:
  selector:
    app: yolo
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
#Frontend Service Loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: yolo-client-svc
spec:
  selector:
    app: yolo
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer